In [1]:
import torch

In [5]:
x = torch.randn((2,2), requires_grad=True)
x

tensor([[-0.3628,  0.4189],
        [-1.4480, -0.9070]], requires_grad=True)

In [7]:
y = x ** 5
y

tensor([[-6.2873e-03,  1.2898e-02],
        [-6.3648e+00, -6.1385e-01]], grad_fn=<PowBackward0>)

In [9]:
y.grad_fn

In [10]:
z = y.mean()
z

tensor(-1.7430, grad_fn=<MeanBackward1>)

In [11]:
print(x.grad)

None


In [12]:
z.backward()

In [13]:
print(x.grad)

tensor([[0.0217, 0.0385],
        [5.4946, 0.8460]])


In [14]:
with torch.no_grad():
    w = y * 5
    print(w.grad)
    w.backward()

None


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn